spring:
    datasource:
        #默认数据源配置
        default:
            username: root
            password: DESW@#sd126
            url: jdbc:mysql://180.97.197.9:3406/child0302?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
    #代码生成配置
    codegen:
        #Mybatis代码
        mybatis:
            config:
                #业务模块
                user:
                    #使用的数据源名称
                    dataSourceName: default
                    javaModel:
                        #model源码输出目录
                        targetProject: src/main/java
                        #model所在包名
                        targetPackage: com.penglecode.xmodule.usercenter.model
                    xmlMapper:
                        #XxxMapper.xml源码输出目录
                        targetProject: src/main/java
                        #XxxMapper.xml所在包名
                        targetPackage: com.penglecode.xmodule.usercenter.mapper
                    daoMapper:
                        #XxxMapper.java源码输出目录
                        targetProject: src/main/java
                        #XxxMapper.java所在包名
                        targetPackage: com.penglecode.xmodule.usercenter.mapper
                    #模块表定义
                    tables:
                        -   tableName: belongs
                            domainObjectName: Belongs
                            modelName: 所属信息
                            modelAlias: Belongs
                            modelCommentAuthor: Customized-Mybatis-Generator
                            insertModelColumns: ['id', 'uuid', 'user_uuid', 'province_uuid', 'city_uuid', 'area_uuid', 'school_uuid', 'grade_uuid', 'class_uuid', 'child_uuid', 'type', 'created_time', 'modified_time', 'charged_type']
                            exampleQueryConditions: {'id': 'eq', 'uuid': 'eq', 'user_uuid': 'eq', 'school_uuid': 'eq', 'grade_uuid': 'eq', 'class_uuid': 'eq', 'type': 'eq'}


        #Service代码
        service:
            config:
                #业务模块
                user:
                    jinterface:
                        #服务接口源码输出目录
                        targetProject: src/main/java
                        #服务接口所在包名
                        targetPackage: com.penglecode.xmodule.usercenter.service
                    jimplement:
                        #服务实现源码输出目录
                        targetProject: src/main/java
                        #服务实现所在包名
                        targetPackage: com.penglecode.xmodule.usercenter.service.impl

        #Controller代码
        controller:
            config:
                #业务模块
                user:
                    #Controller源码输出目录
                    targetProject: src/main/java
                    #Controller所在包名
                    targetPackage: com.penglecode.xmodule.usercenter.web.controller
                    #Controller继承的超类(可以不配置)
                    extendsClass: com.penglecode.xmodule.common.web.servlet.support.HttpApiResourceSupport