spring:
    datasource:
        #默认数据源配置
        default: 
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/xmodule?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    #代码生成配置
    codegen:
        #Mybatis代码
        mybatis: 
            config:
                #业务模块
                order: 
                    #使用的数据源名称
                    dataSourceName: default
                    javaModel:
                        #model源码输出目录
                        targetProject: src/main/java
                        #model所在包名
                        targetPackage: com.penglecode.xmodule.ordercenter.model
                    xmlMapper:
                        #XxxMapper.xml源码输出目录
                        targetProject: src/main/java
                        #XxxMapper.xml所在包名
                        targetPackage: com.penglecode.xmodule.ordercenter.mapper
                    daoMapper:
                        #XxxMapper.java源码输出目录
                        targetProject: src/main/java
                        #XxxMapper.java所在包名
                        targetPackage: com.penglecode.xmodule.ordercenter.mapper
                    #模块表定义
                    tables:
                        -   tableName: cg_order
                            domainObjectName: Order
                            modelName: 订单
                            modelAlias: Order
                            modelCommentAuthor: Mybatis-Generator
                            insertModelColumns: ['total_amount', 'freight_amount', 'order_time', 'customer_id', 'payment_type', 'status', 'remark']
                            exampleQueryConditions: {total_amount: 'gte,lte', order_time: 'gte,lte', customer_id: 'eq', payment_type: 'eq', status: 'eq', remark: 'like'}

                        -   tableName: cg_order_detail
                            domainObjectName: OrderDetail
                            modelName: 订单明细
                            modelAlias: OrderDetail
                            modelCommentAuthor: Mybatis-Generator
                            insertModelColumns: ['order_id', 'product_id', 'product_name', 'product_url', 'unit_price', 'quantity', 'freight_amount', 'sub_total_amount']
                            exampleQueryConditions: {'order_id': 'eq', 'product_id': 'eq', 'product_name': 'like', 'unit_price': 'gte,lte', 'sub_total_amount': 'gte,lte'}



        #Service代码
        service: 
            config:
                #业务模块
                order: 
                    jinterface:
                        #服务接口源码输出目录
                        targetProject: src/main/java
                        #服务接口所在包名
                        targetPackage: com.penglecode.xmodule.ordercenter.service
                    jimplement:
                        #服务实现源码输出目录
                        targetProject: src/main/java
                        #服务实现所在包名
                        targetPackage: com.penglecode.xmodule.ordercenter.service.impl
                        
        #Controller代码
        controller: 
            config:
                #业务模块
                order: 
                    #Controller源码输出目录
                    targetProject: src/main/java
                    #Controller所在包名
                    targetPackage: com.penglecode.xmodule.ordercenter.web.controller
                    #Controller继承的超类(可以不配置)
                    extendsClass: com.penglecode.xmodule.common.web.servlet.support.HttpApiResourceSupport